// <auto-generated />
using System;
using Chess.LoginSignUp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chess.LoginSignUp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251111015525_updateData")]
    partial class updateData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chess.LoginSignUp.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            ID = new Guid("9fd17824-0d56-49d5-ad6d-2a924bf16110"),
                            Name = "Admin"
                        },
                        new
                        {
                            ID = new Guid("13dec387-3b5e-4331-8799-662c8797c3df"),
                            Name = "Guest"
                        });
                });

            modelBuilder.Entity("Chess.LoginSignUp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = new Guid("12f07c12-c32d-4f19-8744-fb6085cfb977"),
                            Email = "admin@example.com",
                            ID = 0,
                            LastName = "Admin",
                            Name = "Administrator",
                            PasswordHash = new byte[] { 38, 61, 92, 107, 9, 25, 66, 175, 254, 22, 42, 35, 132, 58, 80, 85, 244, 95, 70, 128, 216, 112, 128, 148, 73, 6, 62, 51, 30, 231, 93, 133, 67, 40, 31, 89, 220, 228, 64, 162, 146, 56, 5, 77, 50, 46, 145, 32 },
                            ProfilePicture = new byte[0],
                            RoleID = new Guid("9fd17824-0d56-49d5-ad6d-2a924bf16110"),
                            Username = "admin"
                        },
                        new
                        {
                            UserID = new Guid("3197a298-cff0-4f60-8a72-ba66aafe8390"),
                            Email = "guest@example.com",
                            ID = 0,
                            LastName = "Guest",
                            Name = "Guest User",
                            PasswordHash = new byte[] { 12, 67, 122, 59, 10, 136, 40, 73, 208, 102, 210, 116, 39, 38, 2, 252, 162, 152, 66, 198, 160, 21, 213, 193, 175, 188, 199, 47, 217, 207, 114, 107, 68, 210, 112, 145, 123, 69, 163, 117, 193, 9, 162, 79, 114, 235, 211, 86 },
                            ProfilePicture = new byte[0],
                            RoleID = new Guid("13dec387-3b5e-4331-8799-662c8797c3df"),
                            Username = "guest"
                        },
                        new
                        {
                            UserID = new Guid("c7eaea73-c0ae-46f7-88d9-200cedce4069"),
                            Email = "user1@example.com",
                            ID = 0,
                            LastName = "LastOne",
                            Name = "User One",
                            PasswordHash = new byte[] { 192, 175, 151, 123, 86, 185, 100, 143, 209, 105, 248, 58, 137, 140, 93, 148, 142, 180, 47, 42, 56, 31, 39, 190, 223, 196, 161, 149, 100, 148, 132, 158, 137, 228, 136, 73, 150, 36, 241, 164, 22, 5, 8, 111, 99, 107, 208, 244 },
                            ProfilePicture = new byte[0],
                            RoleID = new Guid("13dec387-3b5e-4331-8799-662c8797c3df"),
                            Username = "user1"
                        },
                        new
                        {
                            UserID = new Guid("12847732-fb74-4b2a-a739-ecfca4c83c49"),
                            Email = "user2@example.com",
                            ID = 0,
                            LastName = "LastTwo",
                            Name = "User Two",
                            PasswordHash = new byte[] { 48, 153, 193, 100, 217, 233, 46, 51, 14, 31, 82, 120, 159, 61, 199, 217, 182, 14, 112, 42, 195, 189, 126, 137, 136, 246, 28, 215, 234, 188, 107, 234, 20, 146, 91, 208, 128, 153, 103, 18, 156, 53, 130, 136, 97, 165, 219, 98 },
                            ProfilePicture = new byte[0],
                            RoleID = new Guid("13dec387-3b5e-4331-8799-662c8797c3df"),
                            Username = "user2"
                        },
                        new
                        {
                            UserID = new Guid("b70c4e30-8cc0-414c-b4b1-ba90000d35db"),
                            Email = "user3@example.com",
                            ID = 0,
                            LastName = "LastThree",
                            Name = "User Three",
                            PasswordHash = new byte[] { 179, 157, 10, 126, 24, 36, 162, 152, 127, 67, 111, 135, 5, 2, 121, 36, 241, 191, 28, 114, 144, 43, 236, 6, 43, 134, 126, 203, 161, 206, 64, 89, 41, 203, 243, 121, 224, 15, 196, 79, 57, 152, 55, 173, 214, 85, 27, 192 },
                            ProfilePicture = new byte[0],
                            RoleID = new Guid("13dec387-3b5e-4331-8799-662c8797c3df"),
                            Username = "user3"
                        },
                        new
                        {
                            UserID = new Guid("1de762f5-43fd-4177-967e-715280adce2c"),
                            Email = "usertest@example.com",
                            ID = 0,
                            LastName = "TestLast",
                            Name = "User Test",
                            PasswordHash = new byte[] { 68, 129, 131, 53, 67, 115, 80, 244, 191, 207, 104, 205, 129, 57, 150, 157, 8, 218, 145, 58, 138, 182, 206, 67, 23, 126, 38, 138, 113, 123, 250, 29, 36, 4, 107, 158, 193, 13, 133, 11, 154, 46, 200, 249, 23, 183, 63, 55 },
                            ProfilePicture = new byte[0],
                            RoleID = new Guid("13dec387-3b5e-4331-8799-662c8797c3df"),
                            Username = "usertest"
                        });
                });

            modelBuilder.Entity("Chess.LoginSignUp.Domain.Entities.User", b =>
                {
                    b.HasOne("Chess.LoginSignUp.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Chess.LoginSignUp.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
